name: CI

on:
  push:
    branches: [main]

jobs:
  test-environment:
    name: Deploy

    runs-on: ubuntu-latest
    environment: push

    steps:
      - uses: actions/checkout@v2

      - name: Log deployments
        run: gh api -X GET "repos/$GITHUB_REPOSITORY/deployments" 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
